### PR TITLE
Add support for laravel 5.4

### PR DESCRIPTION
**Pull request by Biptaste**

### CODE REVIEW

**Comment by ejunker** [comment]
Looking forward to seeing this merged so I can upgrade to Laravel 5.4 👍

**Comment by ejunker** [comment]
Thanks @lachlantweedie would also be good to tag a new version so it can be installed with Composer

**Comment by ejunker** [comment]
@lachlantweedie please tag a v2.0.3 release and push it up so that packagist shows a new version and we can install the latest version that works with Laravel 5.4

**Comment by hellotoby** [comment]
@ejunker - New tag is up at v2.0.3

**Pull request merged**
